//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collect_Requests_Table
    {
        public string Collect_Requests { get; set; }
        public string Restaurant_ID { get; set; }
        public string Employee_ID { get; set; }
        public string Max_Preserve_Time { get; set; }
        public string Status { get; set; }
    }
}
