//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGO_Table
    {
        public string NGO_ID { get; set; }
        public string NGO_Name { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
    }
}
