//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant_Table
    {
        public string Restaurant_ID { get; set; }
        public string Restaurant_Name { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
    }
}
